name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_S3_BUCKET_REGION }}

    - name: Copy content to S3
      run: |
        aws s3 sync pelican/output/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/ --delete
